spring:
  application:
    name: eureka-service
server:
  port: 8302
eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8302/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
zuul:
  prefix: /api
  routes:
    db-service:
     path: /db-service/**
     url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      service-id: http://localhost:8301
      
     